name= str(input("Enter your name:"))
age= int(input("Enter your age:"))
add= str(input("Enter your address:"))
print(format("Name: %s"%name))
print(format("age: %d"%age))
print(format("Address: %s"%add))
